sudo: false
language: node_js
node_js:
  - 'stable'
services:
  - postgresql
env:
  - NODE_ENV=test
before_script:
  - psql -c 'create database loanifly-test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '1234';" -U postgres
cache:
  directories:
    - node_modules
script: npm run test
after_success:
  - npm run coveralls
