sudo: false
language: node_js
node_js:
  - 'stable'
services:
  - postgresql
env:
  - NODE_ENV=test
  - TEST_DATABASE = postgres://postgres:1234@localhost:5432/loanifly-test
before_script:
  - psql -c ' CREATE DATABASE loanifly-test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '1234';" -U postgres
cache:
  directories:
    - node_modules
script: npm run test
after_success:
  - npm run coveralls
