sudo: false
language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c ' CREATE DATABASE loanifly-test;' -U postgres;
  - npm run migrate
cache:
  directories:
    - node_modules
script: npm run test
after_success:
  - npm run coveralls
